export enum QUEUE_NAME {
    SIWE_CHECK = 'SIWE_CHECK',
    SIWE_READ = 'SIWE_READ',
    SIWE_GET_NONCE = 'SIWE_GET_NONCE',
    PROFILE_GET = 'PROFILE_GET',
    AUTH_GENERATE_TOKEN = 'AUTH_GENERATE_TOKEN',
    AUTH_REFRESH_TOKEN = 'AUTH_REFRESH_TOKEN',
    USER_CREATE = 'USER_CREATE'
}

export enum ROLE {
    USER = 'user'
}
